### ISSUE TITLE
"name": "Update a dataset - (Error - size is always ero)",

### ISSUE THREAD

**Issue by spreaderman** [umer-ali-khan/mapbox-postman-collections#2]
Firstly, thank you very much for sharing this.  I have learnt a lot from it.  

I noticed for the update of datasets, this is mentioned ""name": "Update a dataset - (Error - size is always ero)".  Is this an expected error return or could you not get it working?  I am also having difficultly updating a dataset so wanted to hear your feedback.

**Comment by umer-ali-khan** [comment]
it's been a long time this repository is not being maintained. Sorry for inconvenience.
